// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFR0XMOrhv2jb7kRUeFPA3evl0eYa6NQ',
    appId: '1:761911361212:web:dafd462316340a0af01ab9',
    messagingSenderId: '761911361212',
    projectId: 'phonepay-bbc74',
    authDomain: 'phonepay-bbc74.firebaseapp.com',
    storageBucket: 'phonepay-bbc74.appspot.com',
    measurementId: 'G-DPBMSHWMKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb44R05sA3_TbjgAERkIPp11TsbYCUgk8',
    appId: '1:761911361212:android:0bec83647182de86f01ab9',
    messagingSenderId: '761911361212',
    projectId: 'phonepay-bbc74',
    storageBucket: 'phonepay-bbc74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnk1vqT-t9re97qf6hHJJHkfDMu9n-46U',
    appId: '1:761911361212:ios:7f6a80b3148912dbf01ab9',
    messagingSenderId: '761911361212',
    projectId: 'phonepay-bbc74',
    storageBucket: 'phonepay-bbc74.appspot.com',
    iosBundleId: 'com.example.phonepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnk1vqT-t9re97qf6hHJJHkfDMu9n-46U',
    appId: '1:761911361212:ios:7f6a80b3148912dbf01ab9',
    messagingSenderId: '761911361212',
    projectId: 'phonepay-bbc74',
    storageBucket: 'phonepay-bbc74.appspot.com',
    iosBundleId: 'com.example.phonepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBFR0XMOrhv2jb7kRUeFPA3evl0eYa6NQ',
    appId: '1:761911361212:web:b4e8187832b17708f01ab9',
    messagingSenderId: '761911361212',
    projectId: 'phonepay-bbc74',
    authDomain: 'phonepay-bbc74.firebaseapp.com',
    storageBucket: 'phonepay-bbc74.appspot.com',
    measurementId: 'G-EQ7W8WGJC1',
  );
}
